Entity/Certification.php
<?php

namespace App\Entity;

use App\Repository\CertificationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=CertificationRepository::class)
 */
class Certification
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
    
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     
     */
    private $Type;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank(message="Date is required")
     */
    private $DatePassage;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     * @Assert\NotBlank(message="Price is required")
     */
    private $Prix;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Description is required")
     * @Assert\Length(
     *      min = 10,    
     *      minMessage = "Description must be at least {{ limit }} characters long",
     * )
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Name is required")
     */
    private $Nom;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="yes")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Entreprise is required")
     */
    private $Entreprise;

    /**
     * @ORM\OneToMany(targetEntity=DemandeCertification::class, mappedBy="Certification", orphanRemoval=true)
     */
    private $yes;



    protected $captchaCode;
    
    public function getCaptchaCode()
    {
      return $this->captchaCode;
    }

    public function setCaptchaCode($captchaCode)
    {
      $this->captchaCode = $captchaCode;
    }


    public function __construct()
    {
        $this->yes = new ArrayCollection();
    }

  


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getDatePassage(): ?\DateTimeInterface
    {
        return $this->DatePassage;
    }

    public function setDatePassage(\DateTimeInterface $DatePassage): self
    {
        $this->DatePassage = $DatePassage;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(int $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getIdSociete(): ?int
    {
        return $this->idSociete;
    }

    public function setIdSociete(int $idSociete): self
    {
        $this->idSociete = $idSociete;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->Entreprise;
    }

    public function setEntreprise(?Entreprise $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }






    /**
     * @return Collection|DemandeCertification[]
     */
    public function getYes(): Collection
    {
        return $this->yes;
    }

    public function addYe(DemandeCertification $ye): self
    {
        if (!$this->yes->contains($ye)) {
            $this->yes[] = $ye;
            $ye->setCertification($this);
        }

        return $this;
    }

    public function removeYe(DemandeCertification $ye): self
    {
        if ($this->yes->removeElement($ye)) {
            // set the owning side to null (unless already changed)
            if ($ye->getCertification() === $this) {
                $ye->setCertification(null);
            }
        }

        return $this;
    }


}

Form/CertificationType.php
<?php

namespace App\Form;

use App\Entity\Certification;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;






use App\Entity\Entreprise;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Captcha\Bundle\CaptchaBundle\Form\Type\CaptchaType;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints\ValidCaptcha;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class CertificationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Type', choiceType::class, [
                 'choices' => [
                  'Informatique' => 'Informatique',
                  'Mecanique' => 'Mecanique',
                  'Electronique' => 'Electronique',

                 ]


            ])
            ->add('DatePassage')
            ->add('Prix')
            ->add('Description')
            ->add('Nom')
            ->add('Entreprise', EntityType::class, [
                'class'=>Entreprise::class,
                'choice_label'=>'nom',
                
                ])   
            ->add('captchaCode', CaptchaType::class, array(
                    'captchaConfig' => 'ExampleCaptchaUserRegistration',
                    'constraints' => [
                        new ValidCaptcha([
                            'message' => 'Invalid captcha, please try again',
                        ]),
                    ],
                ))

                ;
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Certification::class,
        ]);
    }
}

src/Form/CertificationType.php
<?php

namespace App\Form;

use App\Entity\Certification;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;






use App\Entity\Entreprise;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Captcha\Bundle\CaptchaBundle\Form\Type\CaptchaType;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints\ValidCaptcha;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class CertificationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Type')
            ->add('DatePassage')
            ->add('Prix')
            ->add('Description')
            ->add('Nom')
            ->add('Entreprise', EntityType::class, [
                'class'=>Entreprise::class,
                'choice_label'=>'nom',
                
                ])   
            ->add('captchaCode', CaptchaType::class, array(
                    'captchaConfig' => 'ExampleCaptchaUserRegistration',
                    'constraints' => [
                        new ValidCaptcha([
                            'message' => 'Invalid captcha, please try again',
                        ]),
                    ],
                ))

                ;
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Certification::class,
        ]);
    }
}

Controller/CertificationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


use App\Entity\Certification;
use App\Repository\CertificationRepository;
use App\Form\CertificationType;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;


use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;

use Dompdf\Dompdf;
use Dompdf\Options;

use MercurySeries\FlashyBundle\FlashyNotifier;
use App\Repository\CalendarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\ResponseHeaderBag;


class CertificationController extends Controller
{
    
    /**
     * @Route("/certification", name="certification")
     */
    public function index(): Response
    {
        return $this->render('certification/index.html.twig', [
            'controller_name' => 'CertificationController',
        ]);
    }

 

/**
    * @Route("/pdf", name="pdf")
    */
    public function pdf(Request $request){
	
        



// Configure Dompdf according to your needs
$pdfOptions = new Options();
$pdfOptions->set('defaultFont', 'Arial');

// Instantiate Dompdf with our options
$dompdf = new Dompdf($pdfOptions);
	
$repository=$this->getdoctrine()->getrepository(Certification::class);
$allCertification=$repository->findAll();

// Retrieve the HTML generated in our twig file
$html = $this->renderView('Certification/ListeCertPDF.html.twig', [
    'title' => "Welcome to our PDF Test", 'Certifications'=>$allCertification,
]);

// Load HTML to Dompdf
$dompdf->loadHtml($html);

// (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser (force download)
$dompdf->stream("mypdf.pdf", [
    "Attachment" => true
]);
}






    /**
    * @Route("/AjouterCertif", name="AjouterCertif")
    */
    public function ajouterCertif(request $request,FlashyNotifier $flashy){

        $Certification=new Certification();
        $form=$this->createForm(CertificationType::class,$Certification);
        $form->add('Ajouter', SubmitType::class);
        
        $form->handleRequest($request); 
        if ($form->isSubmitted() && $form->isValid() ) 
        { $Certification = $form->getData();
        $em=$this->getDoctrine()->getManager(); 
        $em->persist($Certification);
        $em->flush();
        $flashy->success('Certification created!', 'http://your-awesome-link.com');

        
        return $this->redirectToRoute('AfficherCertif');

        }


        return $this->render('Certification/AjouterCertif.html.twig', [
            'form'=>$form->createView()
        ]);
	}


/**
    * @Route("/AfficherCertif", name="AfficherCertif")
    */
    public function AfficherCertif(Request $request){
		
        $repository=$this->getdoctrine()->getrepository(Certification::class);
        $allCertification=$repository->findAll();
         // Paginate the results of the query
         $Certification = $this->get('knp_paginator')->paginate(
            // Doctrine Query, not results
            $allCertification,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            5
        );



        return $this->render('Certification/AfficherCertif.html.twig', [
            'Certifications'=>$Certification,
        ]);
        
    }

    /**
    * @Route("/AfficherCertifFront", name="AfficherCertifFront")
    */
    public function AfficherCertif1(Request $request){
		
        $repository=$this->getdoctrine()->getrepository(Certification::class);
        $Certification=$repository->findAll();
        $allCertification=$repository->findAll();
        // Paginate the results of the query
        $Certification = $this->get('knp_paginator')->paginate(
           // Doctrine Query, not results
           $allCertification,
           // Define the page parameter
           $request->query->getInt('page', 1),
           // Items per page
           5
       );


        return $this->render('Certification/affFront.html.twig', [
            'Certifications'=>$Certification,
        ]);
        


        
    }








 /**
    * @Route("/ModifierCertif/{id}", name="ModifierCertif")
    */
    public function ModifierCertif(request $request,$id,FlashyNotifier $flashy)


        
        {   $em = $this->getDoctrine()->getManager();
            $Certification= $em->getRepository(Certification::class)->find($id);
            $form=$this->createForm(CertificationType::class,$Certification);
            $form->add('modifier',SubmitType::class);
            $form->handleRequest($request);
            if($form->isSubmitted()&& $form->isValid())
            {
               
                $em->flush();
                $flashy->success('Certification Modifiée!', 'http://your-awesome-link.com');

                return $this->redirectToRoute('AfficherCertif');
            }
    

         return $this->render('certification/ModifierCertif.html.twig', [
            'form'=>$form->createView(),
            
        ]);
       
    }




    /**
     * @Route("/SupprimerCertif/{id}", name="SupprimerCertif")
     */
    public function SupprimerCertif($id,FlashyNotifier $flashy)

    {
        $em = $this->getDoctrine()->getManager();
        $Certification= $em->getRepository(Certification::class)->find($id);
        $em->remove($Certification);
        $em->flush();
        $flashy->success('Certification Supprimée!', 'http://your-awesome-link.com');

        return $this->redirectToRoute('AfficherCertif');

    }



    /**
     * @Route("/home", name="home")
     */
    public function FrontHome(): Response
    {
        return $this->render('/base2.html.twig', [
          //  'controller_name' => 'CertificationController',
        ]);
    }

 /**
    * @Route("/AfficherCertif ", name="SearchCertification")
    */
   public function searchStudentx(Request $request,NormalizerInterface $Normalizer)
   {
       $repository = $this->getDoctrine()->getRepository(Certification::class);
       $requestString=$request->get('searchValue');
       $Certifications = $repository->findCertifByNom($requestString);
       $jsonContent = $Normalizer->normalize($Certifications, 'json',['groups'=>'Certifications']);
       $retour=json_encode($jsonContent);
       return new Response($retour);
     
   }

   /**
     * @Route("/TrieDate", name="TrieDate")
     */
    public function TrieSelonDate(CertificationRepository $repository)
    {
        $Certifications=$this->getdoctrine()->getRepository(Certification::class)->findByDate();
        return $this->render('certification/AffichageTrieDate.html.twig',[
            'Certifications' => $Certifications,
        ]);

    }

     /**
     * @Route("/Informatique", name="Informatique")
     */
    public function AfficherInformatique(CertificationRepository $repository)
    {
        $Certifications=$this->getdoctrine()->getRepository(Certification::class)->findByInf();
        return $this->render('certification/AfficherInformatique.html.twig',[
            'Certifications' => $Certifications,
        ]);

    }
 
    
     /**
     * @Route("/Mecanique", name="Mecanique")
     */
    public function AfficherMecanique(CertificationRepository $repository)
    {
        $Certifications=$this->getdoctrine()->getRepository(Certification::class)->findByMec();
        return $this->render('certification/AfficherMecanique.html.twig',[
            'Certifications' => $Certifications,
        ]);

    }

       /**
     * @Route("/Electronique", name="Electronique")
     */
    public function AfficherElectronique(CertificationRepository $repository)
    {
        $Certifications=$this->getdoctrine()->getRepository(Certification::class)->findByElec();
        return $this->render('certification/AfficherElectronique.html.twig',[
            'Certifications' => $Certifications,
        ]);

    }

    
 



 /**
     * @Route("/stat", name="stat")
     */
public function chartAction(CertificationRepository $repository)

{
  
        $pieChart = new PieChart();
       $Inf = 0;
       $Mec = 0;
       $Elec = 0;

    
    $items= $this->getDoctrine()->getRepository(Certification::class)->findByInf();

    foreach ($items as $item) {
        $Inf += 1;
        
    }       

    $items1= $this->getDoctrine()->getRepository(Certification::class)->findByElec();

    foreach ($items1 as $item) {
        $Elec += 1;
        
    }      
    
    $items2= $this->getDoctrine()->getRepository(Certification::class)->findByMec();

    foreach ($items2 as $item) {
        $Mec += 1;
        
    }  
         
        $pieChart = new PieChart();
        $pieChart->getData()->setArrayToDataTable([
            [ 'JW', 'JAVA/WEB' ],
            [ 'Informatique', $Inf ],
            [ 'Mecanique', $Mec ],
            [ 'Electronique', $Elec ]
        ]);
 
        $pieChart->getOptions()->setTitle('JAVA-WEB CERTIFICATION');
        $pieChart->getOptions()->setHeight(600);
        $pieChart->getOptions()->setWidth(600);
        $pieChart->getOptions()->getTitleTextStyle()->setColor('#07600');
        $pieChart->getOptions()->getTitleTextStyle()->setFontSize(25);
 
         
        return $this->render('certification/stat.html.twig', array(
                'piechart' => $pieChart,
            )
 
        );
    }

    

    /**
     * @Route("/cl", name="cl")
     */
    public function cal00(CertificationRepository $calendar)
    {
        $events = $calendar->findAll();

        $rdvs = [];

        foreach($events as $event){
            $rdvs[] = [

templates/certification/AffichageTrieDate.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CandidatureStageController!{% endblock %}

{% block body %}


<h1> Liste des Certifications </h1>
<br>

<br>

<a href="{{ path('TrieDate') }}"><button class="btn"><i class="fa fa-folder"></i> Les plus proche</button></a>
<a href="{{ path('JAVA') }}"><button class="btn"><i class="fa fa-folder"></i>JAVA</button></a>
<a href="{{ path('WEB') }}"><button class="btn"><i class="fa fa-folder"></i>WEB</button></a>


<br>


<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4c7aaf;
  color: white;
}
</style>
</head>



<table border ="1" id="customers">
<tr>
   <th scope="row">ID</th>
    <th scope="row">TYPE</th>
     <th scope="row">DATE PASSAGE</th>
       <th scope="row">PRIX</th>
       <th scope="row">DESCRIPTION</th>
       <th scope="row">NOM</th>
       <th scope="row">NOM ENTREPRISE</th>
    
</tr>
<tbody id="all">
    {% for certification in Certifications %}
<tr>
   <td>

{{ certification.id }}

   </td>
   <td>

{{ certification.type }}

   </td>

<td>

{{certification.DatePassage |date('d/m/Y')}}

   </td>


<td>

{{certification.prix}}

   </td>
   <td>

{{certification.description}}

   </td>
   <td>

{{certification.nom}}

   </td>

     <td>

{{certification.entreprise.nom}}

   </td>


    <td>



<a href="{{ path('ModifierCertif', {'id': certification.id}) }}"><button class="btn"><i class="fa fa-folder"></i> Modifier</button></a>
  
<a href="{{ path('SupprimerCertif', {'id': certification.id}) }}"<button class="btn"><i class="fa fa-trash"></i> Supprimer</button></a> 


</td>
</tr>


{%endfor%}
</tbody>
	

<tbody id="search">
</tbody>
</table>





{% endblock %}

templates/certification/AfficherCertif.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CandidatureStageController!{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{{ asset('bundles/mercuryseriesflashy/css/flashy.css') }}">


<script src="//code.jquery.com/jquery.js"></script>

	    <script src="{{ asset('bundles/mercuryseriesflashy/js/flashy.js') }}"></script>

<h1> Liste des Certifications </h1>
<br>
<center>
<a href="{{ path('TrieDate') }}"><button class="btn"><i class="fa fa-folder"></i> Les plus proche</button></a>
<a href="{{ path('JAVA') }}"><button class="btn"><i class="fa fa-folder"></i>JAVA</button></a>
<a href="{{ path('WEB') }}"><button class="btn"><i class="fa fa-folder"></i>WEB</button></a>
<a href="{{ path('stat') }}"><button class="btn"><i class="fa fa-folder"></i>STATISTIQUE</button></a>
<a href="{{ path('pdf') }}"><button class="btn"><i class="fa fa-folder"></i>IMPRIMER</button></a>
</center>


<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4c7aaf;
  color: white;
}
</style>
</head>






<table border ="1" id="customers">
<tr>
   <th scope="row">ID</th>
    <th scope="row">TYPE</th>
     <th scope="row">DATE PASSAGE</th>
       <th scope="row">PRIX</th>
       <th scope="row">DESCRIPTION</th>
       <th scope="row">NOM</th>
       <th scope="row">NOM ENTREPRISE</th>
    
</tr>
<tbody id="all">
    {% for certification in Certifications %}
<tr>
   <td>

{{ certification.id }}

   </td>
   <td>

{{ certification.type }}

   </td>

<td>

{{certification.DatePassage |date('d/m/Y')}}

   </td>


<td>

{{certification.prix}}

   </td>
   <td>

{{certification.description}}

   </td>
   <td>

{{certification.nom}}

   </td>

     <td>

{{certification.entreprise.nom}}

   </td>


    <td>



<a href="{{ path('ModifierCertif', {'id': certification.id}) }}"><button class="btn"><i class="fa fa-folder"></i> Modifier</button></a>
  
<a href="{{ path('SupprimerCertif', {'id': certification.id}) }}"<button class="btn"><i class="fa fa-trash"></i> Supprimer</button></a> 


</td>




</tr>


{%endfor%}
</tbody>
	

</td>
</tr>
<td>

<script type="text/javascript">
function imprimer_page(){
  window.print();
}
</script>

<form>
  <input id="impression" name="impression" type="button" onclick="imprimer_page()" value="Imprimer cette page" />
</form>

</td>



</table>
<br>

 <div class="navigation">
 <center>
            {{ knp_pagination_render(Certifications) }}
</center>        
        </div>

       

    {{ include('@MercurySeriesFlashy/flashy.html.twig') }}



{% endblock %}

templates/certification/AfficherJava.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CandidatureStageController!{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<h1> Liste des Certifications </h1>
<br>
<a href="{{ path('TrieDate') }}"><button class="btn"><i class="fa fa-folder"></i> Les plus proche</button></a>
<a href="{{ path('JAVA') }}"><button class="btn"><i class="fa fa-folder"></i>JAVA</button></a>
<a href="{{ path('WEB') }}"><button class="btn"><i class="fa fa-folder"></i>WEB</button></a>

<br>

<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4c7aaf;
  color: white;
}
</style>
</head>



<table border ="1" id="customers">
<tr>
   <th scope="row">ID</th>
    <th scope="row">TYPE</th>
     <th scope="row">DATE PASSAGE</th>
       <th scope="row">PRIX</th>
       <th scope="row">DESCRIPTION</th>
       <th scope="row">NOM</th>
       <th scope="row">NOM ENTREPRISE</th>
    
</tr>
<tbody id="all">
    {% for certification in Certifications %}
<tr>
   <td>

{{ certification.id }}

   </td>
   <td>

{{ certification.type }}

   </td>

<td>

{{certification.DatePassage |date('d/m/Y')}}

   </td>


<td>

{{certification.prix}}

   </td>
   <td>

{{certification.description}}

   </td>
   <td>

{{certification.nom}}

   </td>

     <td>

{{certification.entreprise.nom}}

   </td>


    <td>



<a href="{{ path('ModifierCertif', {'id': certification.id}) }}"><button class="btn"><i class="fa fa-folder"></i> Modifier</button></a>
  
<a href="{{ path('SupprimerCertif', {'id': certification.id}) }}"<button class="btn"><i class="fa fa-trash"></i> Supprimer</button></a> 


</td>
</tr>


{%endfor%}
</tbody>
	

<tbody id="search">
</tbody>


</td>
</tr>
<td>

<script type="text/javascript">
function imprimer_page(){
  window.print();
}
</script>

<form>
  <input id="impression" name="impression" type="button" onclick="imprimer_page()" value="Imprimer cette page" />
</form>

</td>



</table>




</table>





{% endblock %}

templates/certification/ListeCertPDF.html.twig
{% block body %}


<h1> Liste des Certifications </h1>
<br>



<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4c7aaf;
  color: white;
}
</style>
</head>



<table border ="1" id="customers">
<tr>
   <th scope="row">ID</th>
    <th scope="row">TYPE</th>
     <th scope="row">DATE PASSAGE</th>
       <th scope="row">PRIX</th>
       <th scope="row">DESCRIPTION</th>
       <th scope="row">NOM</th>
       <th scope="row">NOM ENTREPRISE</th>
    
</tr>
<tbody id="all">
    {% for certification in Certifications %}
<tr>
   <td>

{{ certification.id }}

   </td>
   <td>

{{ certification.type }}

   </td>

<td>

{{certification.DatePassage |date('d/m/Y')}}

   </td>


<td>

{{certification.prix}}

   </td>
   <td>

{{certification.description}}

   </td>
   <td>

{{certification.nom}}

   </td>

     <td>

{{certification.entreprise.nom}}

   </td>






</tr>


{%endfor%}




{% endblock %}

templates/certification/stat.html.twig
 {% extends 'base.html.twig' %}

{% block title %}Hello CandidatureStageController!{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="robust-content content container-fluid">
<center>
     <div class="content-wrapper">
         <div id="div_chart"></div>
 
         <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
         <script type="text/javascript">
             {{ gc_draw(piechart, 'div_chart') }}
         </script>
 
     </div>
     </center>
 </div>




{% endblock %}